### ISSUE TITLE
door prediction error

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_apps#62]
I'm getting this when I call the `/door_prediction/predict_doors` service:

```
[INFO] [WallTime: 1477061938.217074] requesting prediction for time 1477061926
[ERROR] [WallTime: 1477061938.217488] Error processing request: 'door_prediction' object has no attribute 'doors'
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request)
, self.response_class)\n', '  File "/home/bruno/devel_ws/src/strands_apps/door_pass/scripts/door_prediction.py", line 501, in predict_door_cb\n    return self.get_predict(req.epoch.secs)\n', '  File "/home/bruno/devel_
ws/src/strands_apps/door_pass/scripts/door_prediction.py", line 510, in get_predict\n    if len(self.doors)>0:\n', "AttributeError: 'door_prediction' object has no attribute 'doors'\n"]
```

I think this was working before, any idea what might be going on @Jailander ?

I'm using the TSC maps, everything pretty normal.

**Comment by bfalacerda** [comment]
solved
